name: marketing_attribution
version: '1.0.0'
config-version: 2

profile: 'marketing_attribution'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  marketing_attribution:
    staging:
      materialized: view
      schema: staging
    intermediate:
      materialized: table
      schema: intermediate
    marts:
      materialized: table
      schema: marts